/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentTemplate {
        "dataTopics"?: string;
        "dataType"?: 'cloud' | 'messages' | 'indicator' | 'proxy';
        "setData": (data: any) => Promise<void>;
    }
}
export interface ComponentTemplateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLComponentTemplateElement;
}
declare global {
    interface HTMLComponentTemplateElement extends Components.ComponentTemplate, HTMLStencilElement {
    }
    var HTMLComponentTemplateElement: {
        prototype: HTMLComponentTemplateElement;
        new (): HTMLComponentTemplateElement;
    };
    interface HTMLElementTagNameMap {
        "component-template": HTMLComponentTemplateElement;
    }
}
declare namespace LocalJSX {
    interface ComponentTemplate {
        "dataTopics"?: string;
        "dataType"?: 'cloud' | 'messages' | 'indicator' | 'proxy';
        "onSubscribe"?: (event: ComponentTemplateCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "component-template": ComponentTemplate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-template": LocalJSX.ComponentTemplate & JSXBase.HTMLAttributes<HTMLComponentTemplateElement>;
        }
    }
}
